[phases.setup]
nixPkgs = ["nodejs_20", "vips", "pkg-config"]
aptPkgs = ["libvips-dev"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node backend/server.js"

